title: Griffin Brown
description: Retired alpine ski racer turned data engineer. MSBA graduate building data pipelines and analytics for sport.
logo: "/images/thumbnail.JPG"
github_url: "https://github.com/griffin-brown-95"
linkedin_url: "https://www.linkedin.com/in/griffin-l-brown/"

plugins:
- jekyll-seo-tag

exclude:
- README.md
- LICENSE
- .Rhistory
